version: 2 # CircleCI version
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/postgres:14.1.0
    steps:
      - checkout
      - run: python --version
      - run: docker-compose build