version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build container
          command: |
            cd ~ && docker-compose build

      - run:
          name: Running tests
          command: |
            docker-compose run app sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test"
      - store_artifacts:
          path: test-reports/
          destination: python_app
